# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.13'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/LAW-TF'
    backendServiceArm: 'myserviceconnection'
    backendAzureRmResourceGroupName: 'cicd'
    backendAzureRmStorageAccountName: 'prashcicdtest01'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
  
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/LAW-TF'
    backendServiceArm: 'Visual Studio Enterprise Subscription(6801865b-a083-44fb-b256-d2945feb3039)'
    backendAzureRmResourceGroupName: 'cicd'
    backendAzureRmStorageAccountName: 'prashcicdtest01'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'