# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MySub'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'go version'

- task: CmdLine@2
  inputs:
    script: |
      sudo apt install python3-testresources
      pip3 install checkov
      checkov -d $(System.DefaultWorkingDirectory)/LAW-TF/